### ISSUE TITLE
Handle math-equations with '$' possible?

### ISSUE THREAD

**Issue by Syndesi** [storybooks/marksy#48]
Hi,

I would like to write math equations in markdown like $y = x^2$ and parse it as a custom component and with Mathjax in React.
But is it possible to define a component as just '$' ?

**Comment by Hypnosphi** [comment]
AFAIK, it's not a part of Markdown synthax? Then it looks like a non-trivial task.

After we release `6.0.0` with fix for https://github.com/storybooks/marksy/issues/38, you'll be able to do something like that:

~~~
```math
y = x^2
```
~~~
