### ISSUE TITLE
npm audit issue with version of marked

### ISSUE THREAD

**Issue by cbonaco1** [storybooks/marksy#71]
When running `npm audit`, we are seeing a vulnerability reported with the version of `marked` which `marksy` is consuming. Please see screenshot below:

![npm_audit](https://user-images.githubusercontent.com/8948249/56052128-a8912f80-5d1e-11e9-9145-03a51ed490a2.png)

According to the npm advisory [here](https://www.npmjs.com/advisories/812/versions), please update the version of `marked` to 0.6.2 or later.

**Comment by janisknets** [comment]
Hi, having the same issue, would love to see this resolved, as I don't really like to see warnings in my builds :)

**Comment by christianalfoni** [comment]
Hi guys! I have updated to latest marked and released new version now, 7.0.0 :)
